CREATE TABLE USUARIOS(
id_usuario NUMBER PRIMARY KEY,
nombre_usuario VARCHAR2 (50) NOT NULL,
apellido_usuario VARCHAR2 (50) NOT NULL,
mail_usuario VARCHAR2 (100) NOT NULL,
contrasena VARCHAR2 (100) NOT NULL,
fecha_registro DATE NOT NULL);

CREATE TABLE ROL(
id_rol NUMBER PRIMARY KEY,
nombre_rol VARCHAR2(50) NOT NULL);

CREATE TABLE FOROS(
id_foro NUMBER PRIMARY KEY,
nombre_foro VARCHAR2(100) NOT NULL,
descripcion_foro VARCHAR2(500) NOT NULL);

CREATE TABLE TEMAS(
id_tema NUMBER PRIMARY KEY,
id_foro NUMBER,
id_usuario NUMBER,
titulo_tema VARCHAR2(200) NOT NULL,
primer_mensaje VARCHAR2(4000) NOT NULL,
fecha_creacion DATE NOT NULL,
CONSTRAINT FK_TEMAS_FOROS FOREIGN KEY (id_foro) REFERENCES FOROS(id_foro),
CONSTRAINT FK_TEMAS_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
);

CREATE TABLE POSTS(
id_post NUMBER PRIMARY KEY,
id_tema NUMBER,
id_usuario NUMBER,
contenido_post VARCHAR2(4000) NOT NULL,
fecha_publicacion DATE NOT NULL,
CONSTRAINT FK_POSTS_TEMAS FOREIGN KEY (id_tema) REFERENCES TEMAS(id_tema),
CONSTRAINT FK_POSTS_USUARIOS FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
);

CREATE TABLE MODERADORES(
id_moderador NUMBER PRIMARY KEY,
id_usuario NUMBER,
id_foro NUMBER,
CONSTRAINT FK_MODERADORES_USUARIOS FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario),
CONSTRAINT FK_MODERADORES_FOROS FOREIGN KEY (id_foro) REFERENCES FOROS(id_foro)
);

